/**
 * Intrinsic size of every screenshot the project sheets draw, in pixels.
 *
 * Generated by docs/design/plate-sizes.mjs — do not edit by hand. Re-run it
 * whenever shots.mjs re-takes a screenshot:
 *
 *   node docs/design/plate-sizes.mjs
 */
export const PLATE_SIZES: Record<string, [number, number]> = {
  "/projects/actor-portfolio/about.webp": [2880, 1800],
  "/projects/actor-portfolio/cover.webp": [2880, 1800],
  "/projects/actor-portfolio/experience.webp": [2880, 2216],
  "/projects/actor-portfolio/gallery.webp": [2880, 2110],
  "/projects/actor-portfolio/sizesheet.webp": [2880, 1800],
  "/projects/codemaker-lab/about.webp": [2880, 3224],
  "/projects/codemaker-lab/contact.webp": [2880, 1730],
  "/projects/codemaker-lab/cover.webp": [2880, 1800],
  "/projects/codemaker-lab/plans.webp": [2880, 2778],
  "/projects/codemaker-lab/services.webp": [2880, 3310],
  "/projects/coffee-roastery/about.webp": [2880, 1616],
  "/projects/coffee-roastery/collection.webp": [2880, 2520],
  "/projects/coffee-roastery/contact.webp": [2880, 1654],
  "/projects/coffee-roastery/cover.webp": [2880, 1800],
  "/projects/don-remolo/cover.webp": [2880, 1800],
  "/projects/don-remolo/menu.webp": [2880, 1500],
  "/projects/eckers-solutions/about.webp": [2880, 1656],
  "/projects/eckers-solutions/contact.webp": [2880, 1854],
  "/projects/eckers-solutions/cover.webp": [2880, 1800],
  "/projects/eckers-solutions/paths.webp": [2880, 1004],
  "/projects/eckers-solutions/process.webp": [2880, 844],
  "/projects/eckers-solutions/services.webp": [2880, 1908],
  "/projects/ep-weather/cover.webp": [2880, 1800],
  "/projects/epic-sound-studio/landing.webp": [2880, 1800],
  "/projects/epic-sound-studio/more.webp": [2880, 1800],
  "/projects/epic-sound-studio/player.webp": [2880, 1800],
  "/projects/epic-sound-studio/trending.webp": [2880, 1800],
  "/projects/portfolio-2024/contact.webp": [2880, 1724],
  "/projects/portfolio-2024/cover.webp": [2880, 1800],
  "/projects/portfolio-2024/experience.webp": [2880, 2262],
  "/projects/portfolio-2024/projects.webp": [2880, 2400],
  "/projects/portfolio-2024/skills.webp": [2880, 3870],
  "/projects/react-smart-hooks/npm.webp": [1568, 709],
  "/projects/ts-helpers-kit/npm.webp": [1568, 652],
};

/** How wide the picture is relative to its height. */
export function plateRatio(src: string): number {
  const size = PLATE_SIZES[src];
  // A missing entry means the map is stale, not that the page should break:
  // 16/10 is the shape the shots harness takes covers at.
  return size ? size[0] / size[1] : 1.6;
}
